# Generated by Django 3.0.6 on 2020-05-15 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('for_product', models.BooleanField()),
                ('product_id', models.BigIntegerField()),
                ('branch_address', models.TextField()),
                ('sentiment', models.IntegerField()),
                ('keywords', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('feedback_sum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summarizer.FeedbacksSum')),
            ],
        ),
    ]
